# Generated by Django 3.1.14 on 2024-02-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_auto_20240215_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='typeof',
        ),
    ]
